version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mdm_postgres
    environment:
      POSTGRES_USER: mdm_user
      POSTGRES_PASSWORD: mdm_password
      POSTGRES_DB: mdm_commerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
